sudo: required
services:
- docker
addons:
  ssh_known_hosts:
  - 68.183.231.211
before_install:
- openssl aes-256-cbc -K $encrypted_d7e3b2d2a61d_key -iv $encrypted_d7e3b2d2a61d_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
jobs:
  include:
    - stage: "Tests"
      name: "Testing for client"
      script:
        - docker build -t namhandsome/react-test -f ./client/Dockerfile.dev ./client
        - docker run namhandsome/react-test npm test -- --coverage
    - stage: deploy
      name: "Deploy to server"
      script: .travis/deploy.sh
      if: branch = master
