sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_3abe9649888d_key -iv $encrypted_3abe9649888d_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
- docker build -t namhandsome/react-test -f ./client/Dockerfile.dev ./client
script:
- docker run namhandsome/react-test npm test -- --coverage
deploy:
- provider: script
  skip_cleanup: true
  script: "chmod +x .travis/deploy.sh && .travis/deploy.sh"
  on:
    branch: master
