sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_3abe9649888d_key -iv $encrypted_3abe9649888d_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- docker build -t namhandsome/react-test -f ./client/Dockerfile.dev ./client
script:
- docker run namhandsome/react-test npm test -- --coverage
after_success:
- docker build -t namhandsome/multi-client:latest ./client
- docker build -t namhandsome/multi-nginx:latest ./nginx
- docker build -t namhandsome/multi-server:latest ./server
- docker build -t namhandsome/multi-worker:latest ./worker
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push namhandsome/multi-client
- docker push namhandsome/multi-nginx
- docker push namhandsome/multi-server
- docker push namhandsome/multi-worker
deploy:
- provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh"
  on:
    branch: master
