sudo: required
services:
- docker
addons:
  ssh_known_hosts:
  - 68.183.231.211
before_install:
- openssl aes-256-cbc -K $encrypted_d7e3b2d2a61d_key -iv $encrypted_d7e3b2d2a61d_iv
  -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
- eval  " $ ( ssh-agent -s ) " 
- cp .travis / id_rsa ~ /.ssh/id_rsa
- chmod 600 ~ /.ssh/id_rsa
- ssh-add ~ /.ssh/id_rsa
- docker build -t namhandsome/react-test -f ./client/Dockerfile.dev ./client
script:
- docker run namhandsome/react-test npm test -- --coverage
deploy:
- provider: script
  skip_cleanup: true
  script: chmod +x .travis/deploy.sh && .travis/deploy.sh
  on:
    branch: master
